package model;

/**
 * Created on 20.03.2017.
 */
public enum FieldOfScience {
    NONE,
    ARCHITECTURE,
    BUSINESS_ADMINISTRATION,
    DESIGN,
    IT,
    HISTORY,
    LITERATURE,
    MEDICINE,
    EARTH_SCIENCES,
    ENVIRONMENTAL_SCIENCES,
    PEDAGOGICAL_SCIENCES,
    PSYCHOLOGY,
    PHILOSOPHY,
    JURISPRUDENCE,
    ASTRONOMY,
    BIOLOGY,
    ENGINEERING,
    ARTS,
    LINGUISTICS,
    MATHEMATICS,
    MANAGEMENT,
    MATERIALS_SCIENCE,
    SOCIAL_SCIENCES,
    POLITICS,
    PHYSICS,
    CHEMISTRY,
    ELECTRICAL_AND_ELECTRONICS,
    ECONOMICS
}
